export const people = [
  {
    id: '1',
    name: 'Luke Skywalker',
    height: '172',
    mass: '77',
    hair_color: 'Blond',
    skin_color: 'Fair',
    eye_color: 'Blue',
    gender: 'Male',
  },
  {
    id: '2',
    name: 'C-3PO',
    height: '167',
    mass: '75',
    hair_color: 'N/A',
    skin_color: 'Gold',
    eye_color: 'Yellow',
    gender: 'N/A',
  },
  {
    id: '3',
    name: 'R2-D2',
    height: '96',
    mass: '32',
    hair_color: 'N/A',
    skin_color: 'White, Blue',
    eye_color: 'Red',
    gender: 'N/A',
  },
  {
    id: '4',
    name: 'Darth Vader',
    height: '202',
    mass: '136',
    hair_color: 'None',
    skin_color: 'White',
    eye_color: 'Yellow',
    gender: 'Male',
  },
  {
    id: '5',
    name: 'Leia Organa',
    height: '150',
    mass: '49',
    hair_color: 'Brown',
    skin_color: 'Light',
    eye_color: 'Brown',
    gender: 'Female',
  },
  {
    id: '6',
    name: 'Owen Lars',
    height: '178',
    mass: '120',
    hair_color: 'Brown, Grey',
    skin_color: 'Light',
    eye_color: 'Blue',
    gender: 'Male',
  },
  {
    id: '7',
    name: 'Beru Whitesun Lars',
    height: '165',
    mass: '75',
    hair_color: 'Brown',
    skin_color: 'Light',
    eye_color: 'Blue',
    gender: 'Female',
  },
  {
    id: '8',
    name: 'R5-D4',
    height: '97',
    mass: '32',
    hair_color: 'N/A',
    skin_color: 'White, Red',
    eye_color: 'Red',
    gender: 'N/A',
  },
  {
    id: '9',
    name: 'Mon Mothma',
    height: '174',
    mass: 'Unknown',
    hair_color: 'Auburn',
    skin_color: 'Light',
    eye_color: 'Blue',
    gender: 'Female',
  },
  {
    id: '10',
    name: 'Obi-Wan Kenobi',
    height: '182',
    mass: '77',
    hair_color: 'Auburn, White',
    skin_color: 'Fair',
    eye_color: 'Blue-Gray',
    gender: 'Male',
  },
  {
    id: '11',
    name: 'Anakin Skywalker',
    height: '188',
    mass: '84',
    hair_color: 'Blond',
    skin_color: 'Fair',
    eye_color: 'Blue',
    gender: 'Male',
  },
  {
    id: '12',
    name: 'Luminara Unduli',
    height: '170',
    mass: '56.2',
    hair_color: 'Black',
    skin_color: 'Olive',
    eye_color: 'Blue',
    gender: 'Female',
  },
  {
    id: '13',
    name: 'Chewbacca',
    height: '228',
    mass: '112',
    hair_color: 'Brown',
    skin_color: 'Unknown',
    eye_color: 'Blue',
    gender: 'Male',
  },
  {
    id: '14',
    name: 'Han Solo',
    height: '180',
    mass: '80',
    hair_color: 'Brown',
    skin_color: 'Fair',
    eye_color: 'Brown',
    gender: 'Male',
  },
  {
    id: '15',
    name: 'Aurra Sing',
    height: '164',
    mass: '50',
    hair_color: 'White',
    skin_color: 'Pale White',
    eye_color: 'Green',
    gender: 'Female',
  },
  {
    id: '16',
    name: 'Jabba Desilijic Tiure',
    height: '175',
    mass: '1,358',
    hair_color: 'N/A',
    skin_color: 'Green-Tan, Brown',
    eye_color: 'Orange',
    gender: 'N/A',
  },
  {
    id: '17',
    name: 'Wedge Antilles',
    height: '170',
    mass: '77',
    hair_color: 'Brown',
    skin_color: 'Fair',
    eye_color: 'Hazel',
    gender: 'Male',
  },
  {
    id: '18',
    name: 'Jango Fett',
    height: '183',
    mass: '79',
    hair_color: 'Black',
    skin_color: 'Tan',
    eye_color: 'Brown',
    gender: 'Male',
  },
  {
    id: '19',
    name: 'Yoda',
    height: '66',
    mass: '17',
    hair_color: 'White',
    skin_color: 'Green',
    eye_color: 'Brown',
    gender: 'Male',
  },
  {
    id: '20',
    name: 'Boba Fett',
    height: '183',
    mass: '78.2',
    hair_color: 'Black',
    skin_color: 'Fair',
    eye_color: 'Brown',
    gender: 'Male',
  },
  {
    id: '21',
    name: 'Palpatine',
    height: '170',
    mass: '75',
    hair_color: 'Grey',
    skin_color: 'Pale',
    eye_color: 'Yellow',
    gender: 'Male',
  },
  {
    id: '22',
    name: 'Padmé Amidala',
    height: '165',
    mass: '45',
    hair_color: 'Brown',
    skin_color: 'Light',
    eye_color: 'Brown',
    gender: 'Female',
  },
  {
    id: '23',
    name: 'Mace Windu',
    height: '188',
    mass: '84',
    hair_color: 'None',
    skin_color: 'Dark',
    eye_color: 'Brown',
    gender: 'Male',
  },
  {
    id: '24',
    name: 'Shmi Skywalker',
    height: '163',
    mass: 'Unknown',
    hair_color: 'Black',
    skin_color: 'Fair',
    eye_color: 'Brown',
    gender: 'Female',
  }
]
